version: "3"
services:
  app:
    container_name: dashboard-app
    build:
      context: .
      dockerfile: ./sample-dashboard/Dockerfile
    volumes: 
      - ./sample-dashboard/:/usr/src/sample-dashboard/
    tty: true
  
  front:
    container_name: dashboard-front
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/:/usr/src/frontend/
      - /usr/src/frontend/node_modules
    tty: true
