version: "3"
services:
  app:
    container_name: "dashboard-app"
    build:
      context: .
      dockerfile: "./app/Dockerfile"
    volumes: 
      - "./sample-dashboard/:/usr/src/sample-dashboard/"
    tty: true
